export enum ERROR_CODES {
  // Authentication & Authorization
  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  INVALID_ACCESS_TOKEN = "INVALID_ACCESS_TOKEN",
  INVALID_TOKEN = "INVALID_TOKEN",
  INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  ACCESS_TOKEN_EXPIRED = "ACCESS_TOKEN_EXPIRED",
  REFRESH_TOKEN_EXPIRED = "REFRESH_TOKEN_EXPIRED",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",

  // Validation
  VALIDATION_ERROR = "VALIDATION_ERROR",
  BAD_REQUEST = "BAD_REQUEST",
  // Resource errors
  NOT_FOUND = "NOT_FOUND",

  // Booking-specific errors
  BOOKING_UNAVAILABLE = "BOOKING_UNAVAILABLE",
  BOOKING_CONFLICT = "BOOKING_CONFLICT",
  CHECKIN_DATE_PASSED = "CHECKIN_DATE_PASSED",
  INVALID_DATE_RANGE = "INVALID_DATE_RANGE",
  MAX_GUESTS_EXCEEDED = "MAX_GUESTS_EXCEEDED",

  // Payment errors
  PAYMENT_FAILED = "PAYMENT_FAILED",
  PAYMENT_REQUIRED = "PAYMENT_REQUIRED",
  REFUND_FAILED = "REFUND_FAILED",

  // Server errors
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",

  // Rate limiting
  TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS",
  FETCH_FAILED = "FETCH_FAILED",
}
